global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "user-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["user-service:8000"]

  - job_name: "product-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["product-service:8002"]

  - job_name: "order-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["order-service:8003"]

  - job_name: "payment-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["payment-service:8004"]

  - job_name: "notification-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["notification-service:8005"]
